name: Create firecracker vmlinux

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install building deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libz-dev bin86 bison flex bc libelf-dev libssl-dev wget zip

      - name: Find tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Fetch virtio-accel
        uses: actions/checkout@v2
        with:
          ref: cleanup
          path: virtio-accel

      - name: Fetch linux kernel
        uses: actions/checkout@v2
        with:
          repository: torvalds/linux
          ref: ${{ env.RELEASE_VERSION }}
          fetch-depth: 1
          path: linux

      - name: Fetch firecracker config & build
        working-directory: linux
        run: |
          wget https://raw.githubusercontent.com/firecracker-microvm/firecracker/master/resources/microvm-kernel-x86_64.config -O arch/x86/configs/microvm.config
          touch .config
          make microvm.config
          make vmlinux -j$(nproc)

      - name: Build virtio-accel
        working-directory: virtio-accel
        run: make KDIR=${GITHUB_WORKSPACE}/linux

      - name: Pack release artifacts
        run: tar -cjf virtio_accel-${{ env.RELEASE_VERSION }}.tar linux/vmlinux virtio-accel/virtio_accel.ko

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.NBFC_BUILDER_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release virtio-accel module and kernel for Firecracker
          body: Releasing for kernel ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false

      - name: Upload release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.NBFC_BUILDER_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: virtio_accel-${{ env.RELEASE_VERSION}}.tar
          asset_name: virtio_accel.tar
          asset_content_type: application/zip
